site_name: Cadwork Python Documentation

repo_name: cwapi3d/cwapi3dpython
repo_url: https://github.com/cwapi3d/cwapi3dpython

copyright: Copyright 2024 Cadwork

site_url: https://python.cadwork.dev/

theme:
  name: material
  logo: cw_logo.svg
  favicon: cw_logo.svg
  version: V2025
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - content.code.copy

nav:
  - Home:
      - index.md
      - Getting Started: get_started.md
      - Packages and Modules: modules.md
      - Debugging: debug.md
      - Community: community.md
  - Reference:
      - Attribute Controller: documentation/attribute_controller.md
      - BIM Controller: documentation/bim_controller.md
      - Cadwork:
          - Api Types: documentation/api_types.md 
          - Attribute Display Settings: documentation/attribute_display_settings.md
          - Element Module Properties: documentation/element_module_properties.md
          - Element Type: documentation/element_type.md
          - Standard Element Type: documentation/standard_element_type.md
          - Process Type: documentation/process_type.md
          - Point 3D: documentation/point_3d.md
          - Enumerations: documentation/enums.md
          - Extended Settings: documentation/extended_settings.md
          - Rhino Export Options: documentation/rhino_export_options.md
          - BREP data: documentation/brep_data.md
          - IFC:
              - IFC2x3 Element Type: documentation/ifc_2x3_element_type.md
              - IFC Predefined Type: documentation/ifc_predefined_type.md
              - IFC Options: documentation/ifc_options.md
          - Camera: documentation/camera_data.md
          - Layer Settings: documentation/layer_settings.md
          - Text Object Options: documentation/text_object_options.md
          - Import 3DC Options: documentation/import_3dc_options.md
          - Window Geometry: documentation/window_geometry.md
          - BIMteam Upload Result: documentation/bim_team_upload_result.md
          - Shoulder cut options: documentation/shoulder_options.md
          - Element Filter: documentation/element_filter.md
          - Element Map Query: documentation/element_map_query.md
          - Hit Result: documentation/hit_result.md
          - Coordinate System Data: documentation/coordinate_system_data.md
      - Connector Axis Controller: documentation/connector_axis_controller.md
      - Dimension Controller: documentation/dimension_controller.md
      - Element Controller: documentation/element_controller.md
      - End-Type Controller: documentation/endtype_controller.md
      - File Controller: documentation/file_controller.md
      - Geometry Controller: documentation/geometry_controller.md
      - List Controller: documentation/list_controller.md
      - Machine Controller: documentation/machine_controller.md
      - Material Controller: documentation/material_controller.md
      - Menu Controller: documentation/menu_controller.md
      - Multi Layer Cover Controller: documentation/multi_layer_cover_controller.md
      - Roof Controller: documentation/roof_controller.md
      - Scene Controller: documentation/scene_controller.md
      - Shop Drawing Controller: documentation/shop_drawing_controller.md
      - Utility Controller: documentation/utility_controller.md
      - Visualization Controller: documentation/visualization_controller.md
  - Examples:
      - Geometry: examples/geometry.md
      - Attribute Controller: examples/attribute_example.md
      - BIM Controller: examples/bim_example.md
      - Cadwork: examples/cadwork.md
      - Connector Axis Controller: examples/connector_example.md
      - Element Controller: examples/element_example.md
      - End-Type Controller: examples/endtype_example.md
      - File Controller: examples/file_example.md
      - Geometry Controller: examples/geometry_example.md
      - List Controller: examples/list_example.md
      - Machine Controller: examples/machine_example.md
      - Material Controller: examples/material_example.md
      - Menu Controller: examples/menu_example.md
      - Roof Controller: examples/roof_example.md
      - Scene Controller: examples/scene_example.md
      - Shop Drawing Controller: examples/shop_drawing_example.md
      - Utility Controller: examples/utility_example.md
      - Visualization Controller: examples/visualization_example.md
      - GUI: examples/tk_gui.md
      - Compare: examples/compare.md
  - Videos:
      - videos.md
  - Auto Attributes:
      - auto_attributes.md
  - About:
      - About Guide: about.md
  - Release Notes:
      - Minor Release Notes: release_notes.md
      - Major Release Notes: release_notes_major.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

plugins:
  - search
  - autorefs # Automatically generate references for known types and functions
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # Directory containing Python modules
          options:
            show_signature_annotations: true 
            show_type_annotations: true
            docstring_style: google # Set the docstring style
            cross_reference: true # Enable cross-referencing to make links to classes, methods, and functions
            show_source: false # Disable source code display

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwapi3d
      name: cwapi3d
