from typing import List

from cwapi3d import ifc_2x3_element_type


def get_last_error(code: int) -> str: ...
def get_ifc_guid(element: int) -> str: ...
def set_building_and_storey(elements: List[int], building: str, storey: str) -> None: ...
def get_building(element: int) -> str: ...
def get_storey(element: int) -> str: ...
def clear_errors() -> None: ...
def get_ifc2x3_element_type(element: int) -> ifc_2x3_element_type: ...
def set_ifc2x3_element_type(elements: List[int], ifc_2x3_element_type: ifc_2x3_element_type) -> None: ...
def import_ifc_as_graphical_object(file: str) -> None: ...
def import_bcf(file: str) -> None: ...
def export_bcf(file: str) -> None: ...
def export_ifc(elements: List[int], file: str) -> None: ...
