from typing import List

from cwapi3d import point_3d


def get_last_error(code: int) -> str: ...
def export_2d_wireframe_with_clipboard(clipboard: int, option: bool) -> None: ...
def export_2d_hidden_lines_with_clipboard(clipboard: int, option: bool) -> None: ...
def export_2d_wireframe_with_2dc(file: str, option: bool) -> None: ...
def export_2d_hidden_lines_with_2dc(file: str, option: bool) -> None: ...
def export_wall_with_clipboard(clipboard: int, elements: List[int]) -> None: ...
def export_export_solid_with_clipboard(clipboard: int, elements: List[int]) -> None: ...
def export_piece_by_piece_with_clipboard(clipboard: int, elements: List[int]) -> None: ...
def assign_export_solid(elements: List[int], other_elements: List[int]) -> None: ...
def export_container_with_clipboard(clipboard: int, elements: List[int]) -> None: ...
def add_wall_section_horizontal(number: int, position: point_3d) -> None: ...
def add_wall_section_vertical(number: int, position: point_3d) -> None: ...
def export_wall_with_clipboard_and_presetting(clipboard: int, elements: List[int], file: str) -> None: ...
def load_export_piece_by_piece_settings(file: str) -> None: ...
def save_export_piece_by_piece_settings(file: str) -> None: ...
def clear_errors() -> None: ...
