from typing import List


def get_last_error(code: int) -> str: ...
def export_production_list(elements: List[int], file: str) -> None: ...
def export_part_list(elements: List[int], file: str) -> None: ...
def check_position_numbers_production_list() -> List[int]: ...
def check_position_numbers_part_list() -> List[int]: ...
def clear_errors() -> None: ...
def export_production_list_with_settings(elements: List[int], file: str, settings: str) -> None: ...
def export_part_list_with_settings(elements: List[int], file: str, settings: str) -> None: ...
def generate_new_production_list_numbers(elements: List[int]) -> None: ...
def generate_new_part_list_numbers(elements: List[int]) -> None: ...
def load_production_list_calculation_settings(file: str) -> None: ...
def load_part_list_calculation_settings(file: str) -> None: ...
