from cwapi3d import point_3d


def get_last_error(code: int) -> str: ...
def get_3d_version() -> int: ...
def get_3d_build() -> int: ...
def get_3d_file_name() -> str: ...
def get_3d_file_path() -> str: ...
def set_project_data(code: str, value: str) -> None: ...
def get_project_data(code: str) -> str: ...
def print_error(text: str) -> None: ...
def get_language() -> str: ...
def print_message(text: str) -> None: ...
def get_user_int(text: str) -> int: ...
def get_user_double(text: str) -> float: ...
def get_user_bool(text: str, default: bool) -> bool: ...
def get_user_string(text: str) -> str: ...
def get_project_name() -> str: ...
def set_project_name(value: str) -> None: ...
def get_project_number() -> str: ...
def set_project_number(value: str) -> None: ...
def get_project_part() -> str: ...
def set_project_part(value: str) -> None: ...
def get_project_architect() -> str: ...
def set_project_architect(value: str) -> None: ...
def get_project_customer() -> str: ...
def set_project_customer(value: str) -> None: ...
def get_project_designer() -> str: ...
def set_project_designer(value: str) -> None: ...
def get_project_deadline() -> str: ...
def set_project_deadline(value: str) -> None: ...
def get_project_user_attribute(number: int) -> str: ...
def set_project_user_attribute(number: int, value: str) -> None: ...
def get_project_user_attribute_name(number: int) -> str: ...
def set_project_user_attribute_name(number: int, value: str) -> None: ...
def get_project_latitude() -> float: ...
def get_project_longitude(value: float) -> None: ...
def set_project_latitude() -> float: ...
def set_project_longitude(value: float) -> None: ...
def get_project_address() -> str: ...
def set_project_address(value: float) -> None: ...
def get_project_postal_code() -> str: ...
def set_project_postal_code(value: float) -> None: ...
def get_project_city() -> str: ...
def set_project_city(value: float) -> None: ...
def get_project_country() -> str: ...
def set_project_country(value: float) -> None: ...
def get_3d_userprofil_path() -> str: ...
def get_user_file_from_dialog(type_filter: str) -> str: ...
def get_client_number() -> str: ...
def get_user_point() -> point_3d: ...
def disable_auto_display_refresh() -> None: ...
def enable_auto_display_refresh() -> None: ...
def create_new_guid() -> str: ...
def print_to_console(text: str) -> None: ...
def export_screen_to_image(file: str, factor: int) -> None: ...
def get_new_user_file_from_dialog(type_filter: str) -> str: ...
def api_autostart(name: str, option: int) -> None: ...
def enable_autostart(name: str) -> None: ...
def disable_autostart(name: str) -> None: ...
def check_autostart(name: str) -> bool: ...
def delete_project_data(code: str) -> None: ...
def run_external_program(name: str) -> None: ...
def save_3d_file_silently() -> None: ...
def get_project_guid() -> str: ...
def get_licence_first_part() -> str: ...
def get_licence_second_part() -> str: ...
def show_progress_bar() -> None: ...
def update_progress_bar(status: int) -> None: ...
def hide_progress_bar() -> None: ...
def get_user_color(color: int) -> int: ...
def get_3d_linear_units() -> str: ...
def get_3d_linear_display_units() -> str: ...
def get_3d_angular_units() -> str: ...
def get_3d_angular_display_units() -> str: ...
def get_3d_build_date() -> str: ...
def get_project_elevation() -> float: ...
def set_project_elevation(value: float) -> None: ...
def clear_errors() -> None: ...
def push_check_and_query_data() -> None: ...
def pop_check_and_query_data() -> None: ...
def change_check_and_query_data_to_no_queries() -> None: ...
def change_check_and_query_data_to_queries() -> None: ...
