def get_last_error(code: int) -> str: ...
def export_btl(version: int, file: str) -> None: ...
def export_weinmann_mfb(version: int) -> None: ...
def export_hundegger(version: int) -> None: ...
def clear_errors() -> None: ...
def export_hundegger_with_file_path(version: int, file: str) -> None: ...
