from typing import List


def get_profile_length(profile: int) -> float: ...
def get_edge_length(profile: int, edge: str) -> float: ...
def get_all_caddy_element_ids() -> List[int]: ...
def get_last_error(code: int) -> str: ...
def clear_errors() -> None: ...
