from typing import List


def get_last_error(code: int) -> str: ...
def add_scene(name: str) -> bool: ...
def rename_scene(old_name: str, new_name: str) -> bool: ...
def delete_scene(name: str) -> bool: ...
def add_elements_to_scene(name: str, elements: List[int]) -> bool: ...
def remove_elements_from_scene(name: str, elements: List[int]) -> bool: ...
def get_elements_from_scene(name: str) -> List[int]: ...
def activate_scene(name: str) -> bool: ...
def clear_errors() -> None: ...
