from typing import List


def get_last_error(code: int) -> str: ...
def create_material(name: str) -> int: ...
def get_name(number: int) -> str: ...
def set_name(number: int, value: str) -> None: ...
def get_group(number: int) -> str: ...
def set_group(number: int, value: str) -> None: ...
def get_code(number: int) -> str: ...
def set_code(number: int, value: str) -> None: ...
def get_modulus_elasticity_1(number: int) -> float: ...
def set_modulus_elasticity_1(number: int, value: float) -> None: ...
def get_modulus_elasticity_2(number: int) -> float: ...
def set_modulus_elasticity_2(number: int, value: float) -> None: ...
def get_modulus_elasticity_3(number: int) -> float: ...
def set_modulus_elasticity_3(number: int, value: float) -> None: ...
def get_shear_modulus_1(number: int) -> float: ...
def set_shear_modulus_1(number: int, value: float) -> None: ...
def get_shear_modulus_2(number: int) -> float: ...
def set_shear_modulus_2(number: int, value: float) -> None: ...
def get_price(number: int) -> float: ...
def set_price(number: int, value: float) -> None: ...
def get_price_type(number: int) -> str: ...
def set_price_type(number: int, value: str) -> None: ...
def get_thermal_conductivity(number: int) -> float: ...
def set_thermal_conductivity(number: int, value: float) -> None: ...
def get_heat_capacity(number: int) -> float: ...
def set_heat_capacity(number: int, value: float) -> None: ...
def get_u_min(number: int) -> float: ...
def set_u_min(number: int, value: float) -> None: ...
def get_u_max(number: int) -> float: ...
def set_u_max(number: int, value: float) -> None: ...
def get_fire_resistance_class(number: int) -> str: ...
def set_fire_resistance_class(number: int, value: str) -> None: ...
def get_smoke_class(number: int) -> str: ...
def set_smoke_class(number: int, value: str) -> None: ...
def get_drop_forming_class(number: int) -> str: ...
def set_drop_forming_class(number: int, value: str) -> None: ...
def get_burn_off_rate(number: int) -> float: ...
def set_burn_off_rate(number: int, value: float) -> None: ...
def get_weight(number: int) -> float: ...
def set_weight(number: int, value: float) -> None: ...
def get_weight_type(number: int) -> str: ...
def set_weight_type(number: int, value: str) -> None: ...
def get_material_id(name: str) -> None: ...
def get_all_materials() -> List[int]: ...
def clear_errors() -> None: ...
