from typing import List

from cwapi3d import rgb_color, visibility_state, activation_state


def get_last_error(code: int) -> str: ...
def get_color(number: int) -> int: ...
def set_color(number: int, color: int) -> None: ...
def get_opengl_color(number: int) -> rgb_color: ...
def set_opengl_color(number: int, color: rgb_color) -> None: ...
def is_active(number: int) -> bool: ...
def set_active(elements: List[int]) -> None: ...
def set_inactive(elements: List[int]) -> None: ...
def is_visible(number: int) -> bool: ...
def set_visible(elements: List[int]) -> None: ...
def set_invisible(elements: List[int]) -> None: ...
def is_immutable(number: int) -> bool: ...
def set_immutable(elements: List[int]) -> None: ...
def set_mutable(elements: List[int]) -> None: ...
def show_all_elements() -> None: ...
def hide_all_elements() -> None: ...
def zoom_all_elements() -> None: ...
def zoom_active_elements() -> None: ...
def refresh() -> None: ...
def set_material(elements: List[int], number: int) -> None: ...
def get_material(element: int) -> int: ...
def save_visibility_state() -> visibility_state: ...
def restore_visibility_state(state: visibility_state) -> None: ...
def save_activation_state() -> activation_state: ...
def restore_activation_state(state: activation_state) -> None: ...
def show_view_positive_x() -> None: ...
def show_view_negative_x() -> None: ...
def show_view_positive_y() -> None: ...
def show_view_negative_y() -> None: ...
def show_view_positive_z() -> None: ...
def show_view_negative_z() -> None: ...
def show_view_standard_axo() -> None: ...
def show_view_wireframe() -> None: ...
def show_view_hidden_lines() -> None: ...
def show_view_dashed_hidden_lines() -> None: ...
def show_view_shaded2() -> None: ...
def show_view_shaded1() -> None: ...
def is_selectable(number: int) -> bool: ...
def set_unselectable(elements: List[int]) -> None: ...
def set_selectable(elements: List[int]) -> None: ...
def clear_errors() -> None: ...
