from typing import List


def get_last_error(code: int) -> str: ...
def export_stl_file(elements: List[int], file: str) -> None: ...
def import_step_file(file: str, scale: float) -> List[int]: ...
def import_step_file_with_message_option(file: str, scale: float, option: bool) -> List[int]: ...
def export_webgl(elements: List[int], file: str) -> None: ...
def export_3d_file(elements: List[int], file: str) -> None: ...
def import_sat_file(file: str, scale: float, option: bool) -> List[int]: ...
def import_3dc_file(file: str) -> List[int]: ...
def import_rhino_file(file: str, option: bool) -> List[int]: ...
def export_step_file(elements: List[int], file: str, scale: float, number: int, option: bool) -> None: ...
def import_3dz_file(file: str) -> None: ...
def export_obj_file(elements: List[int], file: str) -> None: ...
def import_sat_file_silently(file: str, scale: float, option: bool) -> List[int]: ...
def export_fbx_file(elements: List[int], file: str, number: int) -> None: ...
def clear_errors() -> None: ...
def import_3dc_file_with_glide(file: str) -> List[int]: ...
def import_btl_file(file: str) -> None: ...
def export_3dc_file(elements: List[int], file: str) -> None: ...
def import_btl_file_for_nesting(file: str) -> None: ...
def export_btl_file_for_nesting(file: str) -> None: ...
def export_rhino_file(elements: List[int], file: str, scale: float, option: bool, number: int) -> None: ...
def export_sat_file(elements: List[int], file: str, scale: float, option: bool, number: int) -> None: ...
