from typing import List

def clear_errors() -> None: ...
def create_new_endtype(arg0: str, arg1: int, arg2: str) -> int: ...
def get_endtype_id(arg0: str) -> int: ...
def get_endtype_id_end(arg0: int) -> int: ...
def get_endtype_id_facet(arg0: int, arg1: int) -> int: ...
def get_endtype_id_start(arg0: int) -> int: ...
def get_endtype_name(arg0: int) -> str: ...
def get_endtype_name_end(arg0: int) -> str: ...
def get_endtype_name_facet(arg0: int, arg1: int) -> str: ...
def get_endtype_name_start(arg0: int) -> str: ...
def get_last_error(arg0: int) -> str: ...
def set_endtype_id_end(arg0: int, arg1: int) -> None: ...
def set_endtype_id_facet(arg0: int, arg1: int, arg2: int) -> None: ...
def set_endtype_id_start(arg0: int, arg1: int) -> None: ...
def set_endtype_name_end(arg0: int, arg1: str) -> None: ...
def set_endtype_name_facet(arg0: int, arg1: str, arg2: int) -> None: ...
def set_endtype_name_start(arg0: int, arg1: str) -> None: ...