name: Publish CwAPI3D Package

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: 'ubuntu-latest'
    environment:
          name: pypi
          url: https://pypi.org/p/cwapi3d
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1.14
