name: Publish CwAPI3D Package

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: 'ubuntu-latest'
    environment:
          name: pypi
          url: https://pypi.org/p/cwapi3d
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4.0.1
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
      - if: steps.changes.outputs.src == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - if: steps.changes.outputs.src == 'true'
        run: pip install build
      - if: steps.changes.outputs.src == 'true'
        run: python -m build
      - if: steps.changes.outputs.src == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1.14
