name: Documentation sanity check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  run-docs-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies (pyproject.toml)
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Install project and runtime dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run pytest
        run: pytest tests/test_docs.py --maxfail=1 --disable-warnings
